Debug: false
DarktableBin: /snap/photoprism/current/photoprism/bin/darktable-cli
AssetsPath: /snap/photoprism/current/photoprism
CachePath: /data/photoprism/cache
OriginalsPath: /data/photoprism/photos/originals
ImportPath: /data/photoprism/photos/import
TempPath: /data/photoprism/temp
HttpServerHost:
HttpHost: unix:/var/snap/photoprism/common/web.socket
HttpMode: release
#HttpPort: 81
HttpPassword:
DatabaseDriver: sqlite
DatabaseDsn: .photoprism.db
Theme: lavendel
Language: english
